### ISSUE TITLE
Error in the example?

### ISSUE THREAD

**Issue by pietercolpaert** [scfc/bison-php#1]
When trying to perform

bison -d calc.y

It returns: calc.y: fatal error: "lalr1.php": %defines is not implemented for PHP

**Comment by scfc** [comment]
Just omit "-d".

**Comment by pietercolpaert** [comment]
Thank you very much!

Been looking at this for quite some time now. I'm clearly not a bison expert :)

**Comment by scfc** [comment]
No problem; on the contrary: As this is experimental alpha code, I prefer getting notified of potential bugs that are not bugs than getting no feedback at all :-).

**Comment by pietercolpaert** [comment]
Alright :)

I have been looking at some parser generators. As the parser I need to build is not very complex I've decided to go for "lime" (a lemon clone for php) instead.

I love your work though!

**Comment by pietercolpaert** [comment]
Just for the record: when installing I came across some problems:
1. I needed to install autopoint

The error message was cryptic enough to make me search for 20 minutes ;)
1.    configure.ac:25: version `UNKNOWN' doesn't follow Gnits standards

I've had to create some .tarball-version files. Not sure which one did the trick.

**Comment by scfc** [comment]
These are probably related to Bison at large. Setting up a development environment for Bison is cumbersome, but of course the idea for end users is to use proper releases which are still very far on the horizon :-).
